version: '3'

services:
  jupyterhub:
    image: jupyterhub
    container_name: jupyterhub
    restart: always
    networks:
      - jupyterhub-network
    volumes:
      - './srv:/srv/jupyterhub'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    ports:
      - '8080:8080'
  sshd:
    image: sshpiper
    container_name: jupyterhub-sshd
    restart: always
    environment:
      - TEMPLATE=jupyter-{{.User}}:22
      - SSHPIPERD_SERVER_KEY_DATA=LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCdXQyRkFtYjVIUndBWm80akFxajEvaEZtNk94Qk5FNUNyWVBhWS9Ma2E0UUFBQUtDaWNydXhvbks3CnNRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQnV0MkZBbWI1SFJ3QVpvNGpBcWoxL2hGbTZPeEJORTVDcllQYVkvTGthNFEKQUFBRUMybGtVT3J3R2xQVEJobnhUUTFsT0FFWUdBdklsWFFoQk9xcUVvYzRIeFdHNjNZVUNadmtkSEFCbWppTUNxUFgrRQpXYm83RUUwVGtLdGc5cGo4dVJyaEFBQUFIRzFoYjNsaFkyaGxia0J0WVc5NVlXTm9aVzVrWlUxQ1VDNXNZVzRCCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
    networks:
      - jupyterhub-network
    ports:
      - '2222:2222'
    stop_signal: SIGKILL
networks:
  jupyterhub-network:
    name: jupyterhub-network
