version: '3'

services:
  jupyterhub:
    image: jupyterhub
    container_name: jupyterhub
    restart: always
    networks:
      - jupyterhub-network
    volumes:
      - './srv:/srv/jupyterhub'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    ports:
      - '8080:8080'
      - '2222:2222'
    environment:
      - SSHPIPERD_SSHMUX_TEMPLATE=jupyter-{{.User}}:22
      - SSHPIPERD_SSHMUX_DB=/srv/jupyterhub/jupyterhub.sqlite
      - SSHPIPERD_SERVER_KEY_DATA=LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBZUIxOXZLTDBUOStBSGJjOE5kT2ZYL2J2dHZDbGw3VEVoa0NKaTBnSWVTd0FBQUxCU1BiVzdVajIxCnV3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQWVCMTl2S0wwVDkrQUhiYzhOZE9mWC9idnR2Q2xsN1RFaGtDSmkwZ0llU3cKQUFBRUFTT1hQSTFQaWt6UWtRcWFVc3puR2l0MXBWYU1QTHgxNy9LbmQ2N1ZhbHFCNEhYMjhvdlJQMzRBZHR6dzEwNTlmOQp1KzI4S1dYdE1TR1FJbUxTQWg1TEFBQUFKbTFoYjNsaFkyaGxia0J0WVc5NVlXTm9aVzVrWlUxaFkwSnZiMnN0VUhKdkxtCnh2WTJGc0FRSURCQVVHQnc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
networks:
  jupyterhub-network:
    name: jupyterhub-network
