#!/command/with-contenv sh

PROG=/opt/conda/bin/jupyterhub-singleuser

cd /home/$MAMBA_USER
export SHELL=/bin/bash
export HOME=/home/$MAMBA_USER

if [ -f /home/$MAMBA_USER/.startup ]; then
    /home/$MAMBA_USER/.startup
fi

exec s6-setuidgid $MAMBA_USER $PROG
